const challengePool = {
  student: {
    male: {
      low: [
        "Pozdravi 5 novih kolega danas",
        "Organizuj grupu za učenje",
        "Vodi prezentaciju pred razredom",
        "Započni razgovor sa profesorom nakon časa",
        "Pridruži se novom klubu ili aktivnosti",
        "Predloži projekat grupi",
        "Pozovi kolege na kafu posle predavanja",
        "Predstavi se nekome ko ti se čini interesantnim",
        "Organizuj zajednički izlazak sa odeljanjem",
        "Prijavi se da vodiš diskusiju na seminaru",
        "Predloži novu ideju na studentskom skupu",
        "Upiši se u novi izborni predmet koji ti je zanimljiv",
        "Pozovi starijeg studenta da ti bude mentor",
        "Organizuj tutoring sesiju za kolege",
        "Prijavi se za studentsku konferenciju",
        "Napravi grupu za zajednički prevoz na fakultet",
        "Predloži poboljšanje u organizaciji nastave",
        "Pozovi kolege da zajedno rade seminarski rad",
        "Prisustvuj gostujućem predavanju i postavi pitanje predavaču",
        "Organizuj kviz veče sa kolegama"
      ],
      medium: [
        "Pozdravi 3 nova kolegu danas",
        "Postavi jedno pitanje na času",
        "Sedni pored nekoga novog u menzi",
        "Pridruži se grupi koja razgovara na pauzi",
        "Komplimenraj nekome danas",
        "Razmeni kontakt sa nekim novim",
        "Učestvuj u diskusiji na času",
        "Pomozi kolegi sa zadatkom koji ne razume",
        "Predloži mesto za sledeće zajedničko učenje",
        "Pitaj kolegu kako mu ide sa ispitima",
        "Pošalji poruku kolegi koga nisi video dugo",
        "Pridruži se studentskom klubu na prvom sastanku",
        "Podeli korisne materijale za učenje sa grupom",
        "Pitaj profesora za savet nakon časa",
        "Dogovori se sa kolegom da zajedno uče za ispit",
        "Nahvali nečiji referat pred grupom",
        "Predloži temu za grupnu diskusiju",
        "Pozovi jednog kolegu da ručate zajedno"
      ],
      high: [
        "Pozdravi jednog kolegu danas",
        "Nasmeši se nekome u hodniku",
        "Odgovori na jedno pitanje u grupi na WhatsAppu",
        "Sedni u razredu pored nekoga",
        "Kaži 'dobar dan' profesoru",
        "Pošalji emoji reakciju na nečiju poruku u grupi",
        "Pitaj kolegu koje je gradivo za sutra",
        "Kaži 'hvala' asistentu posle vežbi",
        "Otvori vrata nekome na faksu",
        "Pitaj nekoga gde je određena učionica"
      ]
    },
    female: {
      low: [
        "Pozdravi 5 novih koleginica danas",
        "Organizuj grupu za učenje",
        "Vodi prezentaciju pred razredom",
        "Započni razgovor sa profesorkom nakon časa",
        "Pridruži se novom klubu ili aktivnosti",
        "Predloži projekat grupi",
        "Pozovi koleginice na kafu posle predavanja",
        "Predstavi se nekome ko ti se čini interesantnim",
        "Organizuj zajednički izlazak sa odeljanjem",
        "Prijavi se da vodiš diskusiju na seminaru",
        "Predloži novu ideju na studentskom skupu",
        "Upiši se u novi izborni predmet koji ti je zanimljiv",
        "Pozovi stariju studentkinju da ti bude mentorica",
        "Organizuj tutoring sesiju za koleginice",
        "Prijavi se za studentsku konferenciju",
        "Napravi grupu za zajednički prevoz na fakultet",
        "Predloži poboljšanje u organizaciji nastave",
        "Pozovi koleginice da zajedno rade seminarski rad",
        "Prisustvuj gostujućem predavanju i postavi pitanje predavaču",
        "Organizuj kviz veče sa kolegama"
      ],
      medium: [
        "Pozdravi 3 nove koleginice danas",
        "Postavi jedno pitanje na času",
        "Sedni pored nekoga novog u menzi",
        "Pridruži se grupi koja razgovara na pauzi",
        "Komplimenraj nekome danas",
        "Razmeni kontakt sa nekim novim",
        "Učestvuj u diskusiji na času",
        "Pomozi koleginici sa zadatkom koji ne razume",
        "Predloži mesto za sledeće zajedničko učenje",
        "Pitaj koleginicu kako joj ide sa ispitima",
        "Pošalji poruku koleginici koju nisi videla dugo",
        "Pridruži se studentskom klubu na prvom sastanku",
        "Podeli korisne materijale za učenje sa grupom",
        "Pitaj profesorku za savet nakon časa",
        "Dogovori se sa kolegicom da zajedno uče za ispit",
        "Nahvali nečiji referat pred grupom",
        "Predloži temu za grupnu diskusiju",
        "Pozovi jednu koleginicu da ručate zajedno"
      ],
      high: [
        "Pozdravi jednu koleginicu danas",
        "Nasmeši se nekome u hodniku",
        "Odgovori na jedno pitanje u grupi na WhatsAppu",
        "Sedni u razredu pored nekoga",
        "Kaži 'dobar dan' profesorki",
        "Pošalji emoji reakciju na nečiju poruku u grupi",
        "Pitaj koleginicu koje je gradivo za sutra",
        "Kaži 'hvala' asistentkini posle vežbi",
        "Otvori vrata nekome na faksu",
        "Pitaj nekoga gde je određena učionica"
      ]
    },
    neutral: {
      low: [
        "Pozdravi 5 novih ljudi danas",
        "Organizuj grupu za učenje",
        "Vodi prezentaciju pred razredom",
        "Započni razgovor sa profesorom nakon časa",
        "Pridruži se novom klubu ili aktivnosti",
        "Predloži projekat grupi",
        "Pozovi kolege na kafu posle predavanja",
        "Predstavi se nekome ko ti se čini interesantnim",
        "Organizuj zajednički izlazak sa odeljanjem",
        "Prijavi se da vodiš diskusiju na seminaru",
        "Predloži novu ideju na studentskom skupu",
        "Upiši se u novi izborni predmet koji ti je zanimljiv",
        "Pozovi starijeg studenta da ti bude mentor",
        "Organizuj tutoring sesiju za kolege",
        "Prijavi se za studentsku konferenciju",
        "Napravi grupu za zajednički prevoz na fakultet",
        "Predloži poboljšanje u organizaciji nastave",
        "Pozovi kolege da zajedno rade seminarski rad",
        "Prisustvuj gostujućem predavanju i postavi pitanje predavaču",
        "Organizuj kviz veče sa kolegama"
      ],
      medium: [
        "Pozdravi 3 nova čoveka danas",
        "Postavi jedno pitanje na času",
        "Sedni pored nekoga novog u menzi",
        "Pridruži se grupi koja razgovara na pauzi",
        "Komplimenraj nekome danas",
        "Razmeni kontakt sa nekim novim",
        "Učestvuj u diskusiji na času",
        "Pomozi kolegi sa zadatkom koji ne razume",
        "Predloži mesto za sledeće zajedničko učenje",
        "Pitaj kolegu kako mu ide sa ispitima",
        "Pošalji poruku kolegi koga nisi video dugo",
        "Pridruži se studentskom klubu na prvom sastanku",
        "Podeli korisne materijale za učenje sa grupom",
        "Pitaj profesora za savet nakon časa",
        "Dogovori se sa kolegom da zajedno uče za ispit",
        "Nahvali nečiji referat pred grupom",
        "Predloži temu za grupnu diskusiju",
        "Pozovi jednog kolegu da ručate zajedno"
      ],
      high: [
        "Pozdravi jednu osobu danas",
        "Nasmeši se nekome u hodniku",
        "Odgovori na jedno pitanje u grupi na WhatsAppu",
        "Sedni u razredu pored nekoga",
        "Kaži 'dobar dan' profesoru",
        "Pošalji emoji reakciju na nečiju poruku u grupi",
        "Pitaj kolegu koje je gradivo za sutra",
        "Kaži 'hvala' asistentu posle vežbi",
        "Otvori vrata nekome na faksu",
        "Pitaj nekoga gde je određena učionica"
      ]
    }
  },

  worker: {
    male: {
      low: [
        "Pozdravi 5 novih kolega danas",
        "Predloži jednu ideju na sastanku",
        "Organizuj team building",
        "Vodi prezentaciju pred timom",
        "Pozovi kolege na ručak",
        "Započni razgovor sa menadžerom",
        "Umreži se sa nekim iz drugog odeljenja",
        "Predloži inovaciju u procesu",
        "Organizuj neformalni sastanak sa timom",
        "Prijavi se da vodiš sledeći projekat",
        "Predloži novu strategiju na timskom sastanku",
        "Pozovi kolegu na after-work piće",
        "Napravi inicijativu za poboljšanje radne kulture",
        "Predloži mentorski program u firmi",
        "Organizuj prezentaciju novih znanja za tim",
        "Postavi pitanje izvršnom direktoru na all-hands sastanku",
        "Predloži saradnju između dva odeljenja",
        "Inicijatiraj razgovor o unapređenju radnih procesa",
        "Pozovi novog kolegu na ručak prvog dana",
        "Predloži firmski događaj ili izlet"
      ],
      medium: [
        "Pozdravi 3 nova kolegu danas",
        "Postavi pitanje na sastanku",
        "Pozovi kolegu na kafu",
        "Započni razgovor sa nekim iz drugog tima",
        "Ponudi pomoć kolegi",
        "Podeli svoju ideju sa timom",
        "Razmeni mišljenje o projektu",
        "Pohvali kolegu za dobro obavljen posao",
        "Pitaj menadžera za povratnu informaciju",
        "Predloži poboljšanje u toku rada",
        "Pošalji email zahvalnosti kolegi",
        "Pitaj kolegu iz drugog odela za savet",
        "Podeli koristan članak sa timom",
        "Ponudi se da pomogneš u projektu koji kasni",
        "Pitaj kolegu kako mu ide sa aktuelnim zadatkom",
        "Predloži efikasniji način za određeni proces",
        "Zatraži sastanak jedan na jedan sa menadžerom"
      ],
      high: [
        "Pozdravi jednog kolegu danas",
        "Nasmeši se kolegi u hodniku",
        "Odgovori na email brzo",
        "Kaži 'dobar dan' na sastanku",
        "Poslušaj tuđe mišljenje bez komentara",
        "Kaži 'hvala' kolegi koji ti je pomogao",
        "Pitaj kolegu kako mu je prošao vikend",
        "Odgovori na Slack/Teams poruku kolege",
        "Kaži 'laku noć' kada odlaziš iz kancelarije",
        "Ponudi kolegi šolju kafe"
      ]
    },
    female: {
      low: [
        "Pozdravi 5 novih koleginica danas",
        "Predloži jednu ideju na sastanku",
        "Organizuj team building",
        "Vodi prezentaciju pred timom",
        "Pozovi koleginice na ručak",
        "Započni razgovor sa menadžerkom",
        "Umreži se sa nekim iz drugog odeljenja",
        "Predloži inovaciju u procesu",
        "Organizuj neformalni sastanak sa timom",
        "Prijavi se da vodiš sledeći projekat",
        "Predloži novu strategiju na timskom sastanku",
        "Pozovi koleginicu na after-work kafu",
        "Napravi inicijativu za poboljšanje radne kulture",
        "Predloži mentorski program u firmi",
        "Organizuj prezentaciju novih znanja za tim",
        "Postavi pitanje izvršnoj direktorki na all-hands sastanku",
        "Predloži saradnju između dva odeljenja",
        "Inicijatiraj razgovor o unapređenju radnih procesa",
        "Pozovi novu koleginicu na ručak prvog dana",
        "Predloži firmski događaj ili izlet"
      ],
      medium: [
        "Pozdravi 3 nove koleginice danas",
        "Postavi pitanje na sastanku",
        "Pozovi koleginicu na kafu",
        "Započni razgovor sa nekim iz drugog tima",
        "Ponudi pomoć koleginici",
        "Podeli svoju ideju sa timom",
        "Razmeni mišljenje o projektu",
        "Pohvali koleginicu za dobro obavljen posao",
        "Pitaj menadžerku za povratnu informaciju",
        "Predloži poboljšanje u toku rada",
        "Pošalji email zahvalnosti koleginici",
        "Pitaj koleginicu iz drugog odela za savet",
        "Podeli koristan članak sa timom",
        "Ponudi se da pomogneš u projektu koji kasni",
        "Pitaj koleginicu kako joj ide sa aktuelnim zadatkom",
        "Predloži efikasniji način za određeni proces",
        "Zatraži sastanak jedan na jedan sa menadžerkom"
      ],
      high: [
        "Pozdravi jednu koleginicu danas",
        "Nasmeši se koleginici u hodniku",
        "Odgovori na email brzo",
        "Kaži 'dobar dan' na sastanku",
        "Poslušaj tuđe mišljenje bez komentara",
        "Kaži 'hvala' koleginici koja ti je pomogla",
        "Pitaj koleginicu kako joj je prošao vikend",
        "Odgovori na Slack/Teams poruku koleginice",
        "Kaži 'laku noć' kada odlaziš iz kancelarije",
        "Ponudi koleginici šolju kafe"
      ]
    },
    neutral: {
      low: [
        "Pozdravi 5 novih ljudi danas",
        "Predloži jednu ideju na sastanku",
        "Organizuj team building",
        "Vodi prezentaciju pred timom",
        "Pozovi kolege na ručak",
        "Započni razgovor sa menadžerom",
        "Umreži se sa nekim iz drugog odeljenja",
        "Predloži inovaciju u procesu",
        "Organizuj neformalni sastanak sa timom",
        "Prijavi se da vodiš sledeći projekat",
        "Predloži novu strategiju na timskom sastanku",
        "Pozovi kolegu na after-work piće",
        "Napravi inicijativu za poboljšanje radne kulture",
        "Predloži mentorski program u firmi",
        "Organizuj prezentaciju novih znanja za tim",
        "Postavi pitanje direktoru na all-hands sastanku",
        "Predloži saradnju između dva odeljenja",
        "Inicijatiraj razgovor o unapređenju radnih procesa",
        "Pozovi novog kolegu na ručak prvog dana",
        "Predloži firmski događaj ili izlet"
      ],
      medium: [
        "Pozdravi 3 nova čoveka danas",
        "Postavi pitanje na sastanku",
        "Pozovi kolegu na kafu",
        "Započni razgovor sa nekim iz drugog tima",
        "Ponudi pomoć kolegi",
        "Podeli svoju ideju sa timom",
        "Razmeni mišljenje o projektu",
        "Pohvali kolegu za dobro obavljen posao",
        "Pitaj menadžera za povratnu informaciju",
        "Predloži poboljšanje u toku rada",
        "Pošalji email zahvalnosti kolegi",
        "Pitaj kolegu iz drugog odela za savet",
        "Podeli koristan članak sa timom",
        "Ponudi se da pomogneš u projektu koji kasni",
        "Pitaj kolegu kako mu ide sa aktuelnim zadatkom",
        "Predloži efikasniji način za određeni proces",
        "Zatraži sastanak jedan na jedan sa menadžerom"
      ],
      high: [
        "Pozdravi jednu osobu danas",
        "Nasmeši se kolegi u hodniku",
        "Odgovori na email brzo",
        "Kaži 'dobar dan' na sastanku",
        "Poslušaj tuđe mišljenje bez komentara",
        "Kaži 'hvala' kolegi koji ti je pomogao",
        "Pitaj kolegu kako mu je prošao vikend",
        "Odgovori na Slack/Teams poruku kolege",
        "Kaži 'laku noć' kada odlaziš iz kancelarije",
        "Ponudi kolegi šolju kafe"
      ]
    }
  },

  unemployed: {
    male: {
      low: [
        "Pozdravi 5 novih ljudi danas",
        "Razgovaraj sa nekim u redu 5 minuta",
        "Pozovi prijatelja na kafu",
        "Pridruži se lokalnoj grupi ili aktivnosti",
        "Započni razgovor u teretani/parku",
        "Upoznaj komšiju",
        "Idi na networking događaj",
        "Prijavi se na volonterski program",
        "Poseti lokalni centar za zapošljavanje i razgovaraj sa savetnikom",
        "Prisustvuj besplatnoj radionici ili predavanju",
        "Pridruži se online zajednici u svojoj struci",
        "Pozovi bivšeg kolegu na kafu",
        "Idi na sajam zapošljavanja",
        "Pridruži se sportskom klubu ili rekreativnoj ligi",
        "Organizuj mali neformalni skup sa prijateljima",
        "Pohađaj kurs ili trening u svojoj oblasti",
        "Postavi pitanje u profesionalnoj Facebook/LinkedIn grupi",
        "Idi na otvoreni dan neke firme",
        "Uključi se u lokalne komunalne aktivnosti",
        "Prijavi se kao mentor mlađima u svom polju"
      ],
      medium: [
        "Pozdravi 3 nova čoveka danas",
        "Započni razgovor sa nekim u redu",
        "Komplimenraj nekome danas",
        "Pozovi prijatelja na šetnju",
        "Predstavi se nekome novom",
        "Razmeni kontakt sa nekim",
        "Započni mali razgovor sa strancem",
        "Pitaj komšiju da li treba pomoć sa nečim",
        "Pošalji poruku starom prijatelju",
        "Pridruži se diskusiji na online forumu",
        "Pitaj nekoga za preporuku knjige ili filma",
        "Dogovori se sa prijateljem za redovne šetnje",
        "Pridruži se grupi na Meetup platformi",
        "Pitaj nekoga za savet o karijeri",
        "Komentariši nečiji post na LinkedIn-u",
        "Pošalji zahvalnicu nekome ko ti je pomogao"
      ],
      high: [
        "Pozdravi jednu osobu danas",
        "Nasmeši se nekome na ulici",
        "Kaži 'dobar dan' komšiji",
        "Odgovori na poruku prijatelja",
        "Izađi napolje na 10 minuta",
        "Sedni u kafiću i naruči nešto",
        "Pitaj prodavca u prodavnici kako mu je dan",
        "Pošalji jedan emoji prijatelju",
        "Prošetaj do parka i sedi 5 minuta",
        "Kaži 'hvala' dostavljaču"
      ]
    },
    female: {
      low: [
        "Pozdravi 5 novih ljudi danas",
        "Razgovaraj sa nekim u redu 5 minuta",
        "Pozovi prijateljicu na kafu",
        "Pridruži se lokalnoj grupi ili aktivnosti",
        "Započni razgovor u teretani/parku",
        "Upoznaj komšinicu",
        "Idi na networking događaj",
        "Prijavi se na volonterski program",
        "Poseti lokalni centar za zapošljavanje i razgovaraj sa savetnikom",
        "Prisustvuj besplatnoj radionici ili predavanju",
        "Pridruži se online zajednici u svojoj struci",
        "Pozovi bivšu koleginicu na kafu",
        "Idi na sajam zapošljavanja",
        "Pridruži se sportskom klubu ili rekreativnoj ligi",
        "Organizuj mali neformalni skup sa prijateljicama",
        "Pohađaj kurs ili trening u svojoj oblasti",
        "Postavi pitanje u profesionalnoj Facebook/LinkedIn grupi",
        "Idi na otvoreni dan neke firme",
        "Uključi se u lokalne komunalne aktivnosti",
        "Prijavi se kao mentorica mlađima u svom polju"
      ],
      medium: [
        "Pozdravi 3 nova čoveka danas",
        "Započni razgovor sa nekim u redu",
        "Komplimenraj nekome danas",
        "Pozovi prijateljicu na šetnju",
        "Predstavi se nekome novom",
        "Razmeni kontakt sa nekim",
        "Započni mali razgovor sa strancem",
        "Pitaj komšinicu da li treba pomoć sa nečim",
        "Pošalji poruku staroj prijateljici",
        "Pridruži se diskusiji na online forumu",
        "Pitaj nekoga za preporuku knjige ili filma",
        "Dogovori se sa prijateljicom za redovne šetnje",
        "Pridruži se grupi na Meetup platformi",
        "Pitaj nekoga za savet o karijeri",
        "Komentariši nečiji post na LinkedIn-u",
        "Pošalji zahvalnicu nekome ko ti je pomogao"
      ],
      high: [
        "Pozdravi jednu osobu danas",
        "Nasmeši se nekome na ulici",
        "Kaži 'dobar dan' komšinici",
        "Odgovori na poruku prijateljice",
        "Izađi napolje na 10 minuta",
        "Sedni u kafiću i naruči nešto",
        "Pitaj prodavačicu u prodavnici kako joj je dan",
        "Pošalji jedan emoji prijateljici",
        "Prošetaj do parka i sedi 5 minuta",
        "Kaži 'hvala' dostavljaču"
      ]
    },
    neutral: {
      low: [
        "Pozdravi 5 novih ljudi danas",
        "Razgovaraj sa nekim u redu 5 minuta",
        "Pozovi prijatelja na kafu",
        "Pridruži se lokalnoj grupi ili aktivnosti",
        "Započni razgovor u teretani/parku",
        "Upoznaj komšiju",
        "Idi na networking događaj",
        "Prijavi se na volonterski program",
        "Poseti lokalni centar za zapošljavanje i razgovaraj sa savetnikom",
        "Prisustvuj besplatnoj radionici ili predavanju",
        "Pridruži se online zajednici u svojoj struci",
        "Pozovi bivšeg kolegu na kafu",
        "Idi na sajam zapošljavanja",
        "Pridruži se sportskom klubu ili rekreativnoj ligi",
        "Organizuj mali neformalni skup sa prijateljima",
        "Pohađaj kurs ili trening u svojoj oblasti",
        "Postavi pitanje u profesionalnoj Facebook/LinkedIn grupi",
        "Idi na otvoreni dan neke firme",
        "Uključi se u lokalne komunalne aktivnosti",
        "Prijavi se kao mentor mlađima u svom polju"
      ],
      medium: [
        "Pozdravi 3 nova čoveka danas",
        "Započni razgovor sa nekim u redu",
        "Komplimenraj nekome danas",
        "Pozovi prijatelja na šetnju",
        "Predstavi se nekome novom",
        "Razmeni kontakt sa nekim",
        "Započni mali razgovor sa strancem",
        "Pitaj komšiju da li treba pomoć sa nečim",
        "Pošalji poruku starom prijatelju",
        "Pridruži se diskusiji na online forumu",
        "Pitaj nekoga za preporuku knjige ili filma",
        "Dogovori se sa prijateljem za redovne šetnje",
        "Pridruži se grupi na Meetup platformi",
        "Pitaj nekoga za savet o karijeri",
        "Komentariši nečiji post na LinkedIn-u",
        "Pošalji zahvalnicu nekome ko ti je pomogao"
      ],
      high: [
        "Pozdravi jednu osobu danas",
        "Nasmeši se nekome na ulici",
        "Kaži 'dobar dan' komšiju",
        "Odgovori na poruku prijatelja",
        "Izađi napolje na 10 minuta",
        "Sedni u kafiću i naruči nešto",
        "Pitaj prodavca u prodavnici kako mu je dan",
        "Pošalji jedan emoji prijatelju",
        "Prošetaj do parka i sedi 5 minuta",
        "Kaži 'hvala' dostavljaču"
      ]
    }
  },

  entrepreneur: {
    male: {
      low: [
        "Kontaktiraj 5 potencijalnih klijenata",
        "Vodi prezentaciju pred investitorima",
        "Organizuj networking događaj",
        "Pozovi poslovnog partnera na ručak",
        "Podeli svoju viziju javno",
        "Započni saradnju sa nekim novim",
        "Prisustvuj poslovnoj konferenciji",
        "Napravi pitch video i podeli ga na LinkedIn-u",
        "Kontaktiraj influensera za potencijalnu saradnju",
        "Organizuj webinar u svojoj oblasti",
        "Prijavi se za poslovnu nagradu ili takmičenje",
        "Pozovi uspešnog preduzetnika na kavu i traži savet",
        "Predloži partnerstvo firmi koja se bavi sličnom oblasti",
        "Napravi intervju sa klijentom i objavi ga",
        "Prisustvuj startup vikend događaju",
        "Postavi gostujući blog post u relevantnoj publikaciji",
        "Kontaktiraj medije za priču o svom biznisu",
        "Organizuj sastanak sa potencijalnim investitorom",
        "Uključi se kao govornik na panelu",
        "Pokrni affiliate program sa partnerima"
      ],
      medium: [
        "Kontaktiraj 2 potencijalna klijenta",
        "Podeli svoju ideju sa nekim novim",
        "Umreži se sa nekim iz tvoje industrije",
        "Zatraži feedback od nekoga",
        "Pozovi poslovnog partnera na kafu",
        "Predstavi se potencijalnom klijentu",
        "Podeli svoj biznis na društvenim mrežama",
        "Odgovori na komentar na poslovnom profilu",
        "Pošalji newsletter postojećim klijentima",
        "Pitaj klijenta za recenziju ili testimonial",
        "Pridruži se preduzetničkoj grupi na LinkedInu",
        "Pošalji cold email potencijalnom partneru",
        "Postavi pitanje u preduzetničkom forumu",
        "Zatraži preporuku od zadovoljnog klijenta",
        "Objavi case study na društvenim mrežama",
        "Dogovori se za besplatni demo sa potencijalnim klijentom"
      ],
      high: [
        "Kontaktiraj jednog potencijalnog klijenta",
        "Odgovori na poslovni email",
        "Podeli jedan post o svom biznisu",
        "Razgovaraj sa jednim klijentom",
        "Zatraži savet od mentora",
        "Lajkuj i komentariši jedan post u svojoj branši",
        "Ažuriraj LinkedIn profil sa jednom novom informacijom",
        "Odgovori na poruku potencijalnog klijenta",
        "Pošalji zahvalnicu posle sastanka",
        "Postavi jedno pitanje u Slack grupi preduzetnika"
      ]
    },
    female: {
      low: [
        "Kontaktiraj 5 potencijalnih klijenata",
        "Vodi prezentaciju pred investitorima",
        "Organizuj networking događaj",
        "Pozovi poslovnu partnerku na ručak",
        "Podeli svoju viziju javno",
        "Započni saradnju sa nekim novim",
        "Prisustvuj poslovnoj konferenciji",
        "Napravi pitch video i podeli ga na LinkedIn-u",
        "Kontaktiraj influenserku za potencijalnu saradnju",
        "Organizuj webinar u svojoj oblasti",
        "Prijavi se za poslovnu nagradu ili takmičenje",
        "Pozovi uspešnu preduzetnici na kafu i traži savet",
        "Predloži partnerstvo firmi koja se bavi sličnom oblasti",
        "Napravi intervju sa klijentom i objavi ga",
        "Prisustvuj startup vikend događaju",
        "Postavi gostujući blog post u relevantnoj publikaciji",
        "Kontaktiraj medije za priču o svom biznisu",
        "Organizuj sastanak sa potencijalnom investitorkinjom",
        "Uključi se kao govornica na panelu",
        "Pokreni affiliate program sa partnericama"
      ],
      medium: [
        "Kontaktiraj 2 potencijalna klijenta",
        "Podeli svoju ideju sa nekim novim",
        "Umreži se sa nekim iz tvoje industrije",
        "Zatraži feedback od nekoga",
        "Pozovi poslovnu partnerku na kafu",
        "Predstavi se potencijalnom klijentu",
        "Podeli svoj biznis na društvenim mrežama",
        "Odgovori na komentar na poslovnom profilu",
        "Pošalji newsletter postojećim klijentima",
        "Pitaj klijenta za recenziju ili testimonial",
        "Pridruži se preduzetničkoj grupi na LinkedInu",
        "Pošalji cold email potencijalnoj partnerki",
        "Postavi pitanje u preduzetničkom forumu",
        "Zatraži preporuku od zadovoljnog klijenta",
        "Objavi case study na društvenim mrežama",
        "Dogovori se za besplatni demo sa potencijalnom klijentom"
      ],
      high: [
        "Kontaktiraj jednog potencijalnog klijenta",
        "Odgovori na poslovni email",
        "Podeli jedan post o svom biznisu",
        "Razgovaraj sa jednim klijentom",
        "Zatraži savet od mentorice",
        "Lajkuj i komentariši jedan post u svojoj branši",
        "Ažuriraj LinkedIn profil sa jednom novom informacijom",
        "Odgovori na poruku potencijalnog klijenta",
        "Pošalji zahvalnicu posle sastanka",
        "Postavi jedno pitanje u Slack grupi preduzetnica"
      ]
    },
    neutral: {
      low: [
        "Kontaktiraj 5 potencijalnih klijenata",
        "Vodi prezentaciju pred investitorima",
        "Organizuj networking događaj",
        "Pozovi poslovnog partnera na ručak",
        "Podeli svoju viziju javno",
        "Započni saradnju sa nekim novim",
        "Prisustvuj poslovnoj konferenciji",
        "Napravi pitch video i podeli ga na LinkedIn-u",
        "Kontaktiraj influensera za potencijalnu saradnju",
        "Organizuj webinar u svojoj oblasti",
        "Prijavi se za poslovnu nagradu ili takmičenje",
        "Pozovi uspešnog preduzetnika na kafu i traži savet",
        "Predloži partnerstvo firmi koja se bavi sličnom oblasti",
        "Napravi intervju sa klijentom i objavi ga",
        "Prisustvuj startup vikend događaju",
        "Postavi gostujući blog post u relevantnoj publikaciji",
        "Kontaktiraj medije za priču o svom biznisu",
        "Organizuj sastanak sa potencijalnim investitorom",
        "Uključi se kao govornik na panelu",
        "Pokreni affiliate program sa partnerima"
      ],
      medium: [
        "Kontaktiraj 2 potencijalna klijenta",
        "Podeli svoju ideju sa nekim novim",
        "Umreži se sa nekim iz tvoje industrije",
        "Zatraži feedback od nekoga",
        "Pozovi poslovnog partnera na kafu",
        "Predstavi se potencijalnom klijentu",
        "Podeli svoj biznis na društvenim mrežama",
        "Odgovori na komentar na poslovnom profilu",
        "Pošalji newsletter postojećim klijentima",
        "Pitaj klijenta za recenziju ili testimonial",
        "Pridruži se preduzetničkoj grupi na LinkedInu",
        "Pošalji cold email potencijalnom partneru",
        "Postavi pitanje u preduzetničkom forumu",
        "Zatraži preporuku od zadovoljnog klijenta",
        "Objavi case study na društvenim mrežama",
        "Dogovori se za besplatni demo sa potencijalnim klijentom"
      ],
      high: [
        "Kontaktiraj jednog potencijalnog klijenta",
        "Odgovori na poslovni email",
        "Podeli jedan post o svom biznisu",
        "Razgovaraj sa jednim klijentom",
        "Zatraži savet od mentora",
        "Lajkuj i komentariši jedan post u svojoj branši",
        "Ažuriraj LinkedIn profil sa jednom novom informacijom",
        "Odgovori na poruku potencijalnog klijenta",
        "Pošalji zahvalnicu posle sastanka",
        "Postavi jedno pitanje u Slack grupi preduzetnika"
      ]
    }
  },

  other: {
    male: {
      low: [
        "Pozdravi 5 novih ljudi danas",
        "Započni razgovor sa nekim novim",
        "Pozovi prijatelja na aktivnost",
        "Pridruži se grupi sa sličnim interesovanjima",
        "Komplimenraj 3 ljudi danas",
        "Započni razgovor u javnom prevozu",
        "Predstavi se nekome interesantnom",
        "Organizuj grupnu aktivnost sa prijateljima",
        "Pridruži se lokalnom hobiju ili radionici",
        "Prisustvuj javnom događaju i upoznaj nekoga",
        "Pozovi komšiju na kafu",
        "Inicijatiraj projekat u lokalnoj zajednici",
        "Prijavi se za amatersku sportsku ligu",
        "Organizuj filmsko veče sa prijateljima",
        "Prijavi se za volonterski rad u svojoj zajednici",
        "Pridruži se čitalačkom klubu",
        "Napravi novi kontakt na društvenoj mreži u svom polju interesovanja",
        "Idi na lokalni kulturni događaj i razgovaraj sa nekim",
        "Prijavi se za kurs nečeg što te oduvek interesovalo",
        "Organizuj roštilj ili zajednički obrok sa komšijama"
      ],
      medium: [
        "Pozdravi 3 nova čoveka danas",
        "Započni mali razgovor sa strancem",
        "Komplimenraj nekome danas",
        "Pozovi prijatelja da se vidite",
        "Predstavi se nekome novom",
        "Razmeni kontakt sa nekim",
        "Započni razgovor online",
        "Pitaj nekoga za preporuku restorana ili aktivnosti",
        "Pošalji poruku prijatelju koga dugo nisi video",
        "Pridruži se diskusiji u online grupi",
        "Pohvali nečiji rad ili trud",
        "Ponudi pomoć nekome u susedstvu",
        "Pitaj nekoga za mišljenje o nečemu",
        "Dogovori se za redovne aktivnosti sa prijateljem",
        "Komentariši nečiji post na društvenim mrežama",
        "Pozovi prijatelja na zajednički sport ili šetnju"
      ],
      high: [
        "Pozdravi jednu osobu danas",
        "Nasmeši se nekome",
        "Odgovori na poruku prijatelja",
        "Kaži 'dobar dan' nekome",
        "Izađi napolje na 15 minuta",
        "Lajkuj objavu prijatelja",
        "Pitaj prodavca kako mu je dan",
        "Pošalji jedan meme prijatelju",
        "Sedi u kafiću i posmatraj ljude 10 minuta",
        "Kaži 'hvala' nekome ko ti je pomogao"
      ]
    },
    female: {
      low: [
        "Pozdravi 5 novih ljudi danas",
        "Započni razgovor sa nekim novim",
        "Pozovi prijateljicu na aktivnost",
        "Pridruži se grupi sa sličnim interesovanjima",
        "Komplimenraj 3 ljudi danas",
        "Započni razgovor u javnom prevozu",
        "Predstavi se nekome interesantnom",
        "Organizuj grupnu aktivnost sa prijateljicama",
        "Pridruži se lokalnom hobiju ili radionici",
        "Prisustvuj javnom događaju i upoznaj nekoga",
        "Pozovi komšinicu na kafu",
        "Inicijatiraj projekat u lokalnoj zajednici",
        "Prijavi se za amatersku sportsku ligu",
        "Organizuj filmsko veče sa prijateljicama",
        "Prijavi se za volonterski rad u svojoj zajednici",
        "Pridruži se čitalačkom klubu",
        "Napravi novi kontakt na društvenoj mreži u svom polju interesovanja",
        "Idi na lokalni kulturni događaj i razgovaraj sa nekim",
        "Prijavi se za kurs nečeg što te oduvek interesovalo",
        "Organizuj zajednički obrok sa komšinicama"
      ],
      medium: [
        "Pozdravi 3 nova čoveka danas",
        "Započni mali razgovor sa strancem",
        "Komplimenraj nekome danas",
        "Pozovi prijateljicu da se vidite",
        "Predstavi se nekome novom",
        "Razmeni kontakt sa nekim",
        "Započni razgovor online",
        "Pitaj nekoga za preporuku restorana ili aktivnosti",
        "Pošalji poruku prijateljici kuju dugo nisi videla",
        "Pridruži se diskusiji u online grupi",
        "Pohvali nečiji rad ili trud",
        "Ponudi pomoć nekome u susedstvu",
        "Pitaj nekoga za mišljenje o nečemu",
        "Dogovori se za redovne aktivnosti sa prijateljicom",
        "Komentariši nečiji post na društvenim mrežama",
        "Pozovi prijateljicu na zajednički sport ili šetnju"
      ],
      high: [
        "Pozdravi jednu osobu danas",
        "Nasmeši se nekome",
        "Odgovori na poruku prijateljice",
        "Kaži 'dobar dan' nekome",
        "Izađi napolje na 15 minuta",
        "Lajkuj objavu prijateljice",
        "Pitaj prodavačicu kako joj je dan",
        "Pošalji jedan meme prijateljici",
        "Sedi u kafiću i posmatraj ljude 10 minuta",
        "Kaži 'hvala' nekome ko ti je pomogao"
      ]
    },
    neutral: {
      low: [
        "Pozdravi 5 novih ljudi danas",
        "Započni razgovor sa nekim novim",
        "Pozovi prijatelja na aktivnost",
        "Pridruži se grupi sa sličnim interesovanjima",
        "Komplimenraj 3 ljudi danas",
        "Započni razgovor u javnom prevozu",
        "Predstavi se nekome interesantnom",
        "Organizuj grupnu aktivnost sa prijateljima",
        "Pridruži se lokalnom hobiju ili radionici",
        "Prisustvuj javnom događaju i upoznaj nekoga",
        "Pozovi komšiju na kafu",
        "Inicijatiraj projekat u lokalnoj zajednici",
        "Prijavi se za amatersku sportsku ligu",
        "Organizuj filmsko veče sa prijateljima",
        "Prijavi se za volonterski rad u svojoj zajednici",
        "Pridruži se čitalačkom klubu",
        "Napravi novi kontakt na društvenoj mreži u svom polju interesovanja",
        "Idi na lokalni kulturni događaj i razgovaraj sa nekim",
        "Prijavi se za kurs nečeg što te oduvek interesovalo",
        "Organizuj roštilj ili zajednički obrok sa komšijama"
      ],
      medium: [
        "Pozdravi 3 nova čoveka danas",
        "Započni mali razgovor sa strancem",
        "Komplimenraj nekome danas",
        "Pozovi prijatelja da se vidite",
        "Predstavi se nekome novom",
        "Razmeni kontakt sa nekim",
        "Započni razgovor online",
        "Pitaj nekoga za preporuku restorana ili aktivnosti",
        "Pošalji poruku prijatelju koga dugo nisi video",
        "Pridruži se diskusiji u online grupi",
        "Pohvali nečiji rad ili trud",
        "Ponudi pomoć nekome u susedstvu",
        "Pitaj nekoga za mišljenje o nečemu",
        "Dogovori se za redovne aktivnosti sa prijateljem",
        "Komentariši nečiji post na društvenim mrežama",
        "Pozovi prijatelja na zajednički sport ili šetnju"
      ],
      high: [
        "Pozdravi jednu osobu danas",
        "Nasmeši se nekome",
        "Odgovori na poruku prijatelja",
        "Kaži 'dobar dan' nekome",
        "Izađi napolje na 15 minuta",
        "Lajkuj objavu prijatelja",
        "Pitaj prodavca kako mu je dan",
        "Pošalji jedan meme prijatelju",
        "Sedi u kafiću i posmatraj ljude 10 minuta",
        "Kaži 'hvala' nekome ko ti je pomogao"
      ]
    }
  }
};

export default challengePool;